import time
import bindings.topNumRow as tnr
import bindings.upperLetterRow as ulr
import bindings.middleLetterRow as mlr
import bindings.bottomLetterRow as blr
import controllers.keyboardCtrl as kbd
import character.movement.jump as jump
import character.movement.jump_db as jump_db
import character.movement.walk as walk

def main():
    cnt = 0
    kbd.Tap([tnr.key_3])
    time.sleep(1)
    kbd.Tap([tnr.key_4])
    time.sleep(1)
    kbd.Tap([tnr.key_5])
    time.sleep(1)
    kbd.Tap([tnr.key_6])
    time.sleep(1)
    kbd.Tap([tnr.key_7])
    time.sleep(1)
    kbd.Tap([tnr.key_8])
    time.sleep(1)
    kbd.Tap([tnr.key_9])
    time.sleep(1)
    kbd.Tap([tnr.key_0])
    time.sleep(1)
    for _ in range(15):
        if cnt == 3:
            time.sleep(0.4)
            kbd.Tap([tnr.key_3])
            time.sleep(1)
            kbd.Tap([tnr.key_4])
            time.sleep(1)
            kbd.Tap([tnr.key_5])
            time.sleep(1)
            kbd.Tap([tnr.key_6])
            time.sleep(1)
            cnt = 0
        # right =>
        jump.Up()
        kbd.Tap([mlr.f])
        time.sleep(0.8)
        jump_db.RightWithAttackFor(1)
        time.sleep(0.2)
        jump.RightWithAttackFor(3)
        kbd.Tap([ulr.q])
        time.sleep(0.4)
        jump.RightWithAttackFor(2)
        jump.Up()
        kbd.Tap([mlr.d])
        print("middle 1")
        time.sleep(0.2)
        jump.RightWithAttackFor(2)
        time.sleep(0.1)
        jump.Up()
        kbd.Tap([ulr.w])
        time.sleep(0.4)
        jump.RightWithAttackFor(2)
        jump.Up()
        kbd.Tap([mlr.f])
        time.sleep(0.8)
        jump_db.RightWithAttackFor(0.5)
        print("end 1")
        walk.LeftFor(0.5)
        time.sleep(0.3)
        jump.Up()
        kbd.Tap([blr.c])
        time.sleep(1)
        jump_db.LeftWithAttackFor(1)
        time.sleep(0.3)
        jump.LeftWithAttack()
        time.sleep(0.5)
        jump.RightWithAttack()
        time.sleep(1)
        kbd.Tap([ulr.e])
        time.sleep(1)
        jump.Up()
        kbd.Tap([blr.c])
        time.sleep(1)
        jump.RightWithAttack()
        time.sleep(0.5)
        jump.LeftWithAttackFor(4)
        time.sleep(0.6)
        kbd.Tap([ulr.q])
        time.sleep(0.4)
        jump_db.LeftWithAttackFor(1)
        time.sleep(1)
        time.sleep(0.3)
        jump.LeftWithAttack()
        time.sleep(0.5)
        jump.RightWithAttack()
        time.sleep(1)
        jump.Up()
        kbd.Tap([blr.c])
        time.sleep(1)
        jump.LeftWithAttack()
        time.sleep(0.5)
        jump.RightWithAttack()
        time.sleep(1)
        jump_db.LeftWithAttackFor(1)
        time.sleep(0.6)
        walk.RightFor(0.3)
        time.sleep(0.5)
        kbd.Tap([tnr.key_7])
        time.sleep(1)
        kbd.Tap([tnr.key_8])
        time.sleep(1)
        kbd.Tap([tnr.key_9])
        time.sleep(1)
        kbd.Tap([tnr.key_0])
        time.sleep(1)
        kbd.Tap({tnr.key_2})
        time.sleep(0.3)
        kbd.Tap({tnr.key_1})
        time.sleep(0.6)
        kbd.Tap({tnr.key_3})
        cnt += 1


